import random
import math


class drunk:
    def __init__(self, name):
        self.name = name


class drunk_normal(drunk):
    def __init__(self, name):
        super().__init__(name)

    def walk():
        walk_options = [(1,0),(0,1),(-1,0),(0,-1)]  #this is the list of possible paths a drunk_normal can take
                                                    #as coordinates (x,y) in a cartesian plane
        return random.choice(walk_options)          #the function selects one option from the list

    
class coordinate:
    def __init__(self, x,y):                        #it recieves a coordinate as (x,y)
        self.x = x
        self.y = y

    def new_position(self, new_x, new_y):
        return coordinate(self.x + new_x, self.y + new_y)   #sums the new (x,y) values to the previous
                                                            #ones so that the new position in the plane
                                                            #is given
    
    def distance(self, new_coordinate):                 #new_coordinate is an instance of coordinate(x,y)
        change_x = self.x - new_coordinate.x            #change in x is just the difference bewtween former
        change_y = self.y - new_coordinate.y            #x value and the new one. Same for y. 
        distance = math.sqrt(change_x**2+change_y**2)   #the distance between any (x,y) and (xb, yb) points
        return distance                                 #is square_root((x-xb)**2 +(y-yb)**2)


class plane:
    def __init__(self):
        self.coordinates = {}                           #in this dict the coordinates of the drunk_normal will be stored 
    
    def add_drunk(self, drunk, coordinate):             #recieves an instance of drunk and coordinate classes
        self.coordinates[drunk] = coordinate            #updates the dict with a drunk (key) and its coordinate

    def get_coordinate(self, drunk):                    #return the current position (x,y) of a drunk which 
        return self.coordinate[drunk]                   #is the dict's key
    
    def move(self, drunk):
        new_x, new_y = drunk.walk()                     #obtain a new (x,y) coordinate by caling the normal_drunk.walk()
        current_coordinate = self.coordinates[drunk]    #get the current coordinate retrieving the (x,y) 
                                                        #info asociated with the drunk key
        
        new_coordinate = current_coordinate.new_position(new_x, new_y)
        
        """Several steps to explain this last line of code: 
                1). current_coordinate is an instance of the class coordinate.
                    current_coordinate is a coordinate stored in the dict self.coordinates (b), from
                    which [drunk] is the key (a):
                        a). current_coordinate = self.coordinates[drunk]
                        b). self.coordinates[drunk] = coordinate
                2). Given 1, we can use the method new_position from the class coordinate.
                    This method returns a new position by adding the current (x,y) stored in
                    current_coordinate to the (new_x, new_y) generated by calling the drunk,walk() method
                3). So, current_coordinate is the new position resulting from this sum: 
                        (x,y) in current_coordinate + (x,y) from drunk.walk()"""
        
        self.coordinates[drunk] = new_coordinate        #we update the dict in self.coordinates with the new coordinate
